services:
  - type: web
    name: ubm-ocr-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1